version: '3.1'

services:
#   db:
#     image: postgres
#     restart: always
#     ports:
#         - "${PGPORT}:${PGPORT}"
#     environment:
#       POSTGRES_PASSWORD: ${PGPASSWORD}
#       POSTGRES_USER: ${PGUSER}
#       POSTGRES_DB: ${PGDATABASE}
#     volumes:
#         - pg-data:/var/lib/postgresql/data

  redis:
    image: 'bitnami/redis:latest'
    ports:
        - "${REDIS_PORT}:${REDIS_PORT}"
    environment:
        - ALLOW_EMPTY_PASSWORD=yes
    volumes:
        - redis-data:/var/lib/redis

#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080

volumes:
    # pg-data:
    redis-data:
